### ISSUE TITLE
4.8: build failure with musl libc

### ISSUE THREAD

**Issue by hhoffstaette** [joe-editor/joe#115]
While updating my Gentoo musl chroot I was surprised by:
```
main.c: In function 'main':
main.c:758:31: error: assignment of read-only variable 'stdin'
  758 |                         stdin = fopen("/dev/tty", "rb");
      |                               ^
```
Musl does not support [stdin/stdout/stderr reassignment](https://wiki.gentoo.org/wiki/Musl_porting_notes#error:_assignment_of_read-only_variable_.27.5Bstdout.7Cstdin.7Cstderr.5D.27).
In case you're wondering [about the reasons](https://www.openwall.com/lists/musl/2023/07/03/3).

Looks like this was introduced in 359ba5cc3e5426512aeb1a8619f479fe5ba68ae3

**Comment by hhoffstaette** [comment]
This seems to do the trick:
```
--- a/joe/main.c
+++ b/joe/main.c
@@ -754,8 +754,7 @@ int main(int argc, char **real_argv, con
 			cstart ((BW *)maint->curwin->object, NULL, NULL, NULL, NULL, 0, 1, NULL, SHELL_TYPE_RAW);
 			/* Close stdin, so that if user kills the copying the program feeding stdin sees a SIGPIPE */
 			/* It won't if there are any extra file descriptors open */
-			fclose(stdin);
-			stdin = fopen("/dev/tty", "rb");
+			freopen("/dev/tty", "rb", stdin);
 		}
 	}
 
```
The comment might need some adjustment to your liking, but with this it builds and works fine so far. I hope I didn't break anything. `freopen` is pure POSIX and should work everywhere.

**Comment by jhallen** [comment]
This is fixed with pr #116 
I'm debating whether to release JOE 4.9 with this fix, or to just slip it in and rename the current JOE-4.8 a release candidate or something.

**Comment by hhoffstaette** [comment]
Thank you for taking a look! I was mostly looking for confirmation, but good to see that you agree with the fix. Personally I don't mind since we treat Musl as a best-effort platform and can easily add the patch ourselves, but I guess the fix for #118 would be nice for a new release as well. Maybe 4.8.1 :)
